<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="IndustrialJEPA">
<meta name="dcterms.date" content="2026-04-09">

<title>V8: JEPA-Based Bearing RUL Prediction – Mechanical-JEPA Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Mechanical-JEPA Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./08_rul_jepa.html" aria-current="page"> 
<span class="menu-text">V8: RUL Prediction</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation"><span class="header-section-number">1</span> Motivation</a>
  <ul class="collapse">
  <li><a href="#why-rul" id="toc-why-rul" class="nav-link" data-scroll-target="#why-rul"><span class="header-section-number">1.1</span> Why RUL%?</a></li>
  <li><a href="#why-does-elapsed-time-alone-fail" id="toc-why-does-elapsed-time-alone-fail" class="nav-link" data-scroll-target="#why-does-elapsed-time-alone-fail"><span class="header-section-number">1.2</span> Why does elapsed-time alone fail?</a></li>
  </ul></li>
  <li><a href="#data-episode-lifetime-distributions" id="toc-data-episode-lifetime-distributions" class="nav-link" data-scroll-target="#data-episode-lifetime-distributions"><span class="header-section-number">2</span> Data: Episode Lifetime Distributions</a></li>
  <li><a href="#jepa-pretraining" id="toc-jepa-pretraining" class="nav-link" data-scroll-target="#jepa-pretraining"><span class="header-section-number">3</span> JEPA Pretraining</a>
  <ul class="collapse">
  <li><a href="#architecture" id="toc-architecture" class="nav-link" data-scroll-target="#architecture"><span class="header-section-number">3.1</span> Architecture</a></li>
  <li><a href="#loss-curves" id="toc-loss-curves" class="nav-link" data-scroll-target="#loss-curves"><span class="header-section-number">3.2</span> Loss Curves</a></li>
  <li><a href="#embedding-quality" id="toc-embedding-quality" class="nav-link" data-scroll-target="#embedding-quality"><span class="header-section-number">3.3</span> Embedding Quality</a></li>
  </ul></li>
  <li><a href="#sec-baselines" id="toc-sec-baselines" class="nav-link" data-scroll-target="#sec-baselines"><span class="header-section-number">4</span> Baselines: All 11 Methods</a></li>
  <li><a href="#key-comparison-jepalstm-vs-handcraftedlstm" id="toc-key-comparison-jepalstm-vs-handcraftedlstm" class="nav-link" data-scroll-target="#key-comparison-jepalstm-vs-handcraftedlstm"><span class="header-section-number">5</span> Key Comparison: JEPA+LSTM vs Handcrafted+LSTM</a></li>
  <li><a href="#piecewise-label-ablation" id="toc-piecewise-label-ablation" class="nav-link" data-scroll-target="#piecewise-label-ablation"><span class="header-section-number">6</span> Piecewise Label Ablation</a></li>
  <li><a href="#latent-trajectories" id="toc-latent-trajectories" class="nav-link" data-scroll-target="#latent-trajectories"><span class="header-section-number">7</span> Latent Trajectories</a></li>
  <li><a href="#sec-transfer" id="toc-sec-transfer" class="nav-link" data-scroll-target="#sec-transfer"><span class="header-section-number">8</span> Cross-Dataset Transfer</a></li>
  <li><a href="#encoder-analysis" id="toc-encoder-analysis" class="nav-link" data-scroll-target="#encoder-analysis"><span class="header-section-number">9</span> Encoder Analysis</a></li>
  <li><a href="#summary-and-honest-limitations" id="toc-summary-and-honest-limitations" class="nav-link" data-scroll-target="#summary-and-honest-limitations"><span class="header-section-number">10</span> Summary and Honest Limitations</a>
  <ul class="collapse">
  <li><a href="#key-results" id="toc-key-results" class="nav-link" data-scroll-target="#key-results"><span class="header-section-number">10.1</span> Key Results</a></li>
  <li><a href="#honest-limitations" id="toc-honest-limitations" class="nav-link" data-scroll-target="#honest-limitations"><span class="header-section-number">10.2</span> Honest Limitations</a></li>
  <li><a href="#novel-contribution" id="toc-novel-contribution" class="nav-link" data-scroll-target="#novel-contribution"><span class="header-section-number">10.3</span> Novel Contribution</a></li>
  </ul></li>
  
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="08_rul_jepa.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">V8: JEPA-Based Bearing RUL Prediction</h1>
<p class="subtitle lead">Self-supervised pretraining for Remaining Useful Life estimation on FEMTO and XJTU-SY datasets</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>IndustrialJEPA </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="overview">Overview</h2>
<p>This document covers the complete V8 research session:</p>
<ol type="1">
<li>Motivation: why RUL%, why elapsed-time alone fails</li>
<li>Data: episode lifetime distributions, waveform examples</li>
<li>JEPA Pretraining: loss curves, embedding quality, collapse check</li>
<li>Baselines Table: all 11 methods with RMSE <span class="math inline">\(\pm\)</span> std</li>
<li>Key Comparison: JEPA+LSTM vs Handcrafted+LSTM</li>
<li>Piecewise Label Ablation</li>
<li>Per-Episode Analysis</li>
<li>Latent Trajectories</li>
<li>Cross-Dataset Transfer: Temporal Contrastive vs JEPA</li>
<li>Encoder Analysis: what JEPA vs Contrastive learn</li>
<li>Summary and Honest Limitations</li>
</ol>
<pre class="{python}"><code>#| label: setup
#| code-fold: true

import sys
import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

sys.path.insert(0, str(Path('../v8').resolve()))

RESULTS_DIR = Path('../v8/results')
PLOTS_DIR = Path('plots')

plt.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 13,
    'axes.labelsize': 12,
    'figure.dpi': 120,
    'figure.facecolor': 'white',
})</code></pre>
</section>
<section id="motivation" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">1</span> Motivation</h2>
<section id="why-rul" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="why-rul"><span class="header-section-number">1.1</span> Why RUL%?</h3>
<p>We define RUL as a <strong>fraction of remaining life</strong>:</p>
<p><span class="math display">\[\text{RUL}(t) = 1 - \frac{t}{T_{\text{failure}}}\]</span></p>
<p>This normalizes across bearings with very different absolute lifetimes (0.5h to 2.6h in XJTU-SY). A bearing at 50% of its life gets RUL=0.5 regardless of whether it lives 30 minutes or 3 hours.</p>
</section>
<section id="why-does-elapsed-time-alone-fail" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="why-does-elapsed-time-alone-fail"><span class="header-section-number">1.2</span> Why does elapsed-time alone fail?</h3>
<p>A naive predictor using only elapsed time cannot work across machines because:</p>
<ol type="1">
<li><strong>Unknown total lifetime</strong> at test time — we don’t know when failure will occur</li>
<li><strong>High variability</strong> — XJTU-SY lifetimes range 5x (0.5h to 2.6h)</li>
<li><strong>Cross-dataset transfer</strong> — FEMTO bearings run at different loads/speeds than XJTU-SY</li>
</ol>
<p>The elapsed-time baseline achieves RMSE = 0.224 in-domain and 0.367 cross-domain. Signal-based methods must beat these to be useful.</p>
</section>
</section>
<section id="data-episode-lifetime-distributions" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="data-episode-lifetime-distributions"><span class="header-section-number">2</span> Data: Episode Lifetime Distributions</h2>
<pre class="{python}"><code>#| label: fig-lifetimes
#| fig-cap: "Episode lifetime distributions for FEMTO and XJTU-SY run-to-failure datasets. FEMTO lifetimes cluster tightly (CV=0.05); XJTU-SY varies widely (CV=0.46)."

from data_pipeline import load_rul_episodes, episode_train_test_split

all_episodes = load_rul_episodes(['femto', 'xjtu_sy'], verbose=False)

femto_eps = {ep: snaps for ep, snaps in all_episodes.items() if snaps[0]['source'] == 'femto'}
xjtu_eps = {ep: snaps for ep, snaps in all_episodes.items() if snaps[0]['source'] == 'xjtu_sy'}

femto_lifetimes = [snaps[-1]['elapsed_sec'] / 3600 for snaps in femto_eps.values()]
xjtu_lifetimes = [snaps[-1]['elapsed_sec'] / 3600 for snaps in xjtu_eps.values()]
femto_snapshots = [len(snaps) for snaps in femto_eps.values()]
xjtu_snapshots = [len(snaps) for snaps in xjtu_eps.values()]

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

ax = axes[0]
ax.bar(range(len(femto_lifetimes)), sorted(femto_lifetimes), color='steelblue', alpha=0.8, label='FEMTO')
ax.bar(range(len(femto_lifetimes), len(femto_lifetimes)+len(xjtu_lifetimes)),
       sorted(xjtu_lifetimes), color='coral', alpha=0.8, label='XJTU-SY')
ax.axvline(len(femto_lifetimes)-0.5, color='gray', linestyle='--', linewidth=1)
ax.set_xlabel('Episode (sorted by lifetime)')
ax.set_ylabel('Lifetime (hours)')
ax.set_title('Episode Lifetimes: FEMTO vs XJTU-SY')
ax.legend()

ax2 = axes[1]
ax2.hist(femto_snapshots, bins=10, alpha=0.7, color='steelblue', label=f'FEMTO (n={len(femto_eps)})')
ax2.hist(xjtu_snapshots, bins=10, alpha=0.7, color='coral', label=f'XJTU-SY (n={len(xjtu_eps)})')
ax2.set_xlabel('Number of snapshots per episode')
ax2.set_ylabel('Count')
ax2.set_title('Snapshots per Episode')
ax2.legend()

plt.tight_layout()
plt.show()

print(f'FEMTO: {len(femto_eps)} episodes, {min(femto_snapshots)}-{max(femto_snapshots)} snapshots (10s intervals)')
print(f'XJTU-SY: {len(xjtu_eps)} episodes, {min(xjtu_snapshots)}-{max(xjtu_snapshots)} snapshots (60s intervals)')
print(f'FEMTO CV: {np.std(femto_lifetimes)/np.mean(femto_lifetimes):.3f}')
print(f'XJTU-SY CV: {np.std(xjtu_lifetimes)/np.mean(xjtu_lifetimes):.3f}')</code></pre>
<pre class="{python}"><code>#| label: fig-waveforms
#| fig-cap: "Representative vibration waveforms from a FEMTO bearing at different degradation stages. RMS amplitude increases as the bearing approaches failure."

ep_id = list(femto_eps.keys())[0]
snaps = femto_eps[ep_id]
n = len(snaps)

early_idx = n // 10
mid_idx = n // 2
late_idx = int(n * 0.9)

fig, axes = plt.subplots(3, 1, figsize=(12, 6), sharex=True)
labels = [('Early (RUL=0.9)', early_idx, 'steelblue'),
          ('Mid (RUL=0.5)', mid_idx, 'orange'),
          ('Late (RUL=0.1)', late_idx, 'red')]

for ax, (label, idx, color) in zip(axes, labels):
    sig = snaps[idx]['signal'][:1024]
    t = np.arange(len(sig)) / 25600
    ax.plot(t * 1000, sig, color=color, linewidth=0.5, alpha=0.8)
    ax.set_ylabel('Amplitude')
    ax.set_title(label)
    rms = np.sqrt(np.mean(sig**2))
    ax.text(0.02, 0.95, f'RMS={rms:.4f}', transform=ax.transAxes, va='top', fontsize=10, color=color)

axes[-1].set_xlabel('Time (ms)')
plt.suptitle(f'Bearing Waveforms: {ep_id}', y=1.01)
plt.tight_layout()
plt.show()</code></pre>
</section>
<section id="jepa-pretraining" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="jepa-pretraining"><span class="header-section-number">3</span> JEPA Pretraining</h2>
<section id="architecture" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="architecture"><span class="header-section-number">3.1</span> Architecture</h3>
<div id="tbl-architecture" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: JEPA V8 architecture summary
</figcaption>
<div aria-describedby="tbl-architecture-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Specification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input</td>
<td>1024 samples at 12,800 Hz (0.08s), 1 channel</td>
</tr>
<tr class="even">
<td>Patches</td>
<td>16 patches of 64 samples</td>
</tr>
<tr class="odd">
<td>Encoder</td>
<td>ViT-style, <span class="math inline">\(d\)</span>=256, 4 layers, 4 heads</td>
</tr>
<tr class="even">
<td>Target encoder</td>
<td>EMA copy, momentum=0.996</td>
</tr>
<tr class="odd">
<td>Predictor</td>
<td>4-layer Transformer, <span class="math inline">\(d\)</span>=128, sinusoidal PE</td>
</tr>
<tr class="even">
<td>Masking</td>
<td>62.5% (10/16 patches)</td>
</tr>
<tr class="odd">
<td>Loss</td>
<td>L1 on L2-normalized predictions + variance reg (<span class="math inline">\(\lambda\)</span>=0.1)</td>
</tr>
<tr class="even">
<td>Parameters</td>
<td>4.0M (encoder) + 0.9M (predictor)</td>
</tr>
<tr class="odd">
<td>Pretraining data</td>
<td>33,939 windows from 8 bearing sources</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="loss-curves" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="loss-curves"><span class="header-section-number">3.2</span> Loss Curves</h3>
<pre class="{python}"><code>#| label: fig-pretrain
#| fig-cap: "JEPA pretraining loss history. Loss reaches minimum at epoch 2 then oscillates --- characteristic of EMA-based JEPA on heterogeneous multi-source data."

pretrain_img = plt.imread(str(PLOTS_DIR / 'v8_pretrain_history.png'))
fig, ax = plt.subplots(figsize=(10, 5))
ax.imshow(pretrain_img)
ax.axis('off')
plt.tight_layout()
plt.show()</code></pre>
</section>
<section id="embedding-quality" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="embedding-quality"><span class="header-section-number">3.3</span> Embedding Quality</h3>
<pre class="{python}"><code>#| label: embedding-quality

with open(RESULTS_DIR / 'embedding_quality.json') as f:
    eq = json.load(f)

print(f'Max per-dim correlation with RUL:    {eq["z_corrs_max"]:.4f}')
print(f'Mean per-dim correlation with RUL:   {eq["z_corrs_mean"]:.4f}')
print(f'Best handcrafted feature corr:       {eq["hc_corrs_max"]:.4f}')
print(f'Embedding spectral entropy:          {eq["spectral_entropy"]:.4f}')</code></pre>
<p>JEPA embeddings have low per-dim correlation with RUL (0.144) compared to handcrafted spectral centroid (0.585). The JEPA objective learns waveform texture, not the spectral centroid shift that dominates bearing degradation.</p>
</section>
</section>
<section id="sec-baselines" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-baselines"><span class="header-section-number">4</span> Baselines: All 11 Methods</h2>
<pre class="{python}"><code>#| label: tbl-baselines
#| tbl-cap: "RUL prediction results with linear labels. 23 episodes (16 FEMTO + 7 XJTU-SY), 75/25 episode-based split."

with open(RESULTS_DIR / 'rul_baselines_linear.json') as f:
    linear_data = json.load(f)

results = linear_data['results']
time_rmse = linear_data['time_only_rmse']

print(f'Time-only baseline RMSE: {time_rmse:.4f}')
print()
print(f'{"Method":&lt;32} {"RMSE":&gt;8} {"±std":&gt;7} {"vs Time-Only":&gt;14}')
print('-' * 65)

method_order = [
    'constant_mean', 'elapsed_time_linear',
    'envelope_rms_lstm', 'random_jepa_lstm',
    'cnn_lstm_e2e', 'cnn_gru_mha',
    'handcrafted_lstm', 'jepa_lstm',
    'handcrafted_mlp', 'transformer_handcrafted',
]

for method in method_order:
    r = results.get(method, {})
    if 'rmse_mean' in r:
        rmse = r['rmse_mean']
        std = r['rmse_std']
        vs = (time_rmse - rmse) / time_rmse * 100
        print(f'{method:&lt;32} {rmse:8.4f} {std:7.4f} {vs:+13.1f}%')
    elif 'rmse' in r:
        rmse = r['rmse']
        vs = (time_rmse - rmse) / time_rmse * 100
        print(f'{method:&lt;32} {rmse:8.4f} {"":&gt;7} {vs:+13.1f}%')</code></pre>
</section>
<section id="key-comparison-jepalstm-vs-handcraftedlstm" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="key-comparison-jepalstm-vs-handcraftedlstm"><span class="header-section-number">5</span> Key Comparison: JEPA+LSTM vs Handcrafted+LSTM</h2>
<pre class="{python}"><code>#| label: fig-comparison
#| fig-cap: "RUL prediction RMSE across all methods. Left: linear labels. Right: piecewise-linear labels. Red dashed line = elapsed-time-only baseline."

comparison_img = plt.imread(str(PLOTS_DIR / 'v8_rul_comparison.png'))
fig, ax = plt.subplots(figsize=(14, 6))
ax.imshow(comparison_img)
ax.axis('off')
plt.tight_layout()
plt.show()</code></pre>
<pre class="{python}"><code>#| label: statistical-tests

with open(RESULTS_DIR / 'final_comparison.json') as f:
    final = json.load(f)

jepa = final['jepa_lstm']
rnd = final['random_jepa_lstm']
hc = final['hc_lstm']

print('5-seed paired statistical tests:')
print(f'  JEPA+LSTM:        RMSE={jepa["rmse_mean"]:.4f} ± {jepa["rmse_std"]:.4f}  ({jepa["improvement_vs_time"]:+.1f}% vs time)')
print(f'  Random JEPA+LSTM: RMSE={rnd["rmse_mean"]:.4f} ± {rnd["rmse_std"]:.4f}')
print(f'  HC+LSTM:          RMSE={hc["rmse_mean"]:.4f} ± {hc["rmse_std"]:.4f}')
print()
print(f'  JEPA vs Random: p={final["jepa_vs_random_pval"]:.4f} (significant)')
print(f'  JEPA vs HC:     p={final["jepa_vs_hc_pval"]:.4f} (not significant)')</code></pre>
<p>JEPA significantly beats random initialization (<span class="math inline">\(p\)</span>=0.010) confirming the encoder learned useful representations. However, it does <em>not</em> significantly beat handcrafted features (<span class="math inline">\(p\)</span>=0.40).</p>
</section>
<section id="piecewise-label-ablation" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="piecewise-label-ablation"><span class="header-section-number">6</span> Piecewise Label Ablation</h2>
<pre class="{python}"><code>#| label: piecewise-ablation

with open(RESULTS_DIR / 'rul_baselines_piecewise.json') as f:
    piecewise_data = json.load(f)

pw_results = piecewise_data['results']
lin_results = linear_data['results']

print(f'{"Method":&lt;25} {"Linear":&gt;10} {"Piecewise":&gt;12} {"Delta":&gt;8}')
print('-' * 58)

for method in ['jepa_lstm', 'handcrafted_mlp', 'handcrafted_lstm', 'transformer_handcrafted']:
    lr = lin_results.get(method, {})
    pr = pw_results.get(method, {})
    l_rmse = lr.get('rmse_mean', lr.get('rmse', float('nan')))
    p_rmse = pr.get('rmse_mean', pr.get('rmse', float('nan')))
    print(f'{method:&lt;25} {l_rmse:10.4f} {p_rmse:12.4f} {p_rmse - l_rmse:+8.4f}')</code></pre>
<p>Piecewise labels are harder because the constant-RUL healthy phase makes prediction ambiguous — the signal changes but the label stays at 1.0.</p>
</section>
<section id="latent-trajectories" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="latent-trajectories"><span class="header-section-number">7</span> Latent Trajectories</h2>
<pre class="{python}"><code>#| label: fig-latent
#| fig-cap: "JEPA embedding trajectories for FEMTO episodes projected to 2D via PCA. Color indicates RUL% (green=healthy, red=failed). Arrows show degradation direction."

lat_img = plt.imread(str(PLOTS_DIR / 'v8_latent_trajectories.png'))
fig, ax = plt.subplots(figsize=(12, 6))
ax.imshow(lat_img)
ax.axis('off')
plt.tight_layout()
plt.show()</code></pre>
</section>
<section id="sec-transfer" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-transfer"><span class="header-section-number">8</span> Cross-Dataset Transfer</h2>
<pre class="{python}"><code>#| label: fig-cross-dataset
#| fig-cap: "Cross-dataset RUL transfer. Temporal contrastive pretraining significantly outperforms JEPA for FEMTO-to-XJTU and XJTU-to-FEMTO transfer."

cd_img = plt.imread(str(PLOTS_DIR / 'v8_cross_dataset.png'))
fig, ax = plt.subplots(figsize=(12, 5))
ax.imshow(cd_img)
ax.axis('off')
plt.tight_layout()
plt.show()</code></pre>
<pre class="{python}"><code>#| label: cross-dataset-numbers

with open(RESULTS_DIR / 'cross_dataset_contrastive.json') as f:
    cd_cont = json.load(f)

print(f'{"Configuration":&lt;22} {"Elapsed":&gt;9} {"JEPA":&gt;9} {"Contrastive":&gt;13} {"Gain":&gt;7}')
print('-' * 65)

for key, label in [('femto_to_femto', 'FEMTO-&gt;FEMTO'), ('xjtu_to_xjtu', 'XJTU-&gt;XJTU'),
                    ('femto_to_xjtu', 'FEMTO-&gt;XJTU'), ('xjtu_to_femto', 'XJTU-&gt;FEMTO')]:
    r = cd_cont[key]
    gain = (r['jepa_lstm_rmse'] - r['contrastive_lstm_rmse']) / r['jepa_lstm_rmse'] * 100
    print(f'{label:&lt;22} {r["elapsed"]:9.4f} {r["jepa_lstm_rmse"]:9.4f} {r["contrastive_lstm_rmse"]:13.4f} {gain:+6.1f}%')

with open(RESULTS_DIR / 'final_10seed_results.json') as f:
    f10 = json.load(f)
fxj = f10['femto_to_xjtu']
print(f'\nFEMTO-&gt;XJTU (10 seeds): Contrastive {fxj["contrastive_mean"]:.3f}±{fxj["contrastive_std"]:.3f} vs JEPA {fxj["jepa_mean"]:.3f}±{fxj["jepa_std"]:.3f}, p={fxj["contrastive_vs_jepa_pval"]:.2e}')</code></pre>
</section>
<section id="encoder-analysis" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="encoder-analysis"><span class="header-section-number">9</span> Encoder Analysis</h2>
<pre class="{python}"><code>#| label: fig-encoder
#| fig-cap: "What each encoder learns. JEPA captures waveform texture; temporal contrastive captures spectral centroid shift (the dominant degradation indicator)."

enc_img = plt.imread(str(PLOTS_DIR / 'v8_encoder_analysis.png'))
fig, ax = plt.subplots(figsize=(14, 8))
ax.imshow(enc_img)
ax.axis('off')
plt.tight_layout()
plt.show()</code></pre>
<div id="tbl-encoder" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-encoder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Encoder representation quality comparison
</figcaption>
<div aria-describedby="tbl-encoder-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>JEPA</th>
<th>Contrastive</th>
<th>HC (spectral centroid)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PC1 corr w/ RUL</td>
<td>0.186</td>
<td>0.648</td>
<td>0.585</td>
</tr>
<tr class="even">
<td>PC1 corr w/ spectral centroid</td>
<td>0.071</td>
<td>0.856</td>
<td>1.000</td>
</tr>
<tr class="odd">
<td>Max per-dim corr w/ RUL</td>
<td>0.144</td>
<td>0.648</td>
<td>0.585</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Mechanistic explanation</strong>: JEPA’s objective (predict masked patches from context) learns waveform texture and periodicity. Temporal contrastive’s objective (early snapshots negative to late) forces the encoder to learn what <em>changes</em> over bearing life — primarily the spectral centroid shift as surface roughness increases.</p>
</section>
<section id="summary-and-honest-limitations" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="summary-and-honest-limitations"><span class="header-section-number">10</span> Summary and Honest Limitations</h2>
<section id="key-results" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="key-results"><span class="header-section-number">10.1</span> Key Results</h3>
<div id="tbl-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Summary of main results
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 22%">
<col style="width: 16%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th>Method</th>
<th>RMSE</th>
<th>vs Time-Only</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>In-domain</td>
<td>Time-only baseline</td>
<td>0.224</td>
<td>—</td>
</tr>
<tr class="even">
<td>In-domain</td>
<td>JEPA+LSTM (5 seeds)</td>
<td>0.189 <span class="math inline">\(\pm\)</span> 0.015</td>
<td>+15.8%</td>
</tr>
<tr class="odd">
<td>In-domain</td>
<td>Transformer+HC</td>
<td>0.070 <span class="math inline">\(\pm\)</span> 0.006</td>
<td>+68.8%</td>
</tr>
<tr class="even">
<td>In-domain</td>
<td><strong>Hybrid (JEPA+HC)</strong></td>
<td><strong>0.055 <span class="math inline">\(\pm\)</span> 0.004</strong></td>
<td><strong>+75.5%</strong></td>
</tr>
<tr class="odd">
<td>Cross-domain</td>
<td>JEPA+LSTM (10 seeds)</td>
<td>0.279 <span class="math inline">\(\pm\)</span> 0.006</td>
<td>+23.9%</td>
</tr>
<tr class="even">
<td>Cross-domain</td>
<td><strong>Contrastive+LSTM</strong></td>
<td><strong>0.227 <span class="math inline">\(\pm\)</span> 0.015</strong></td>
<td><strong>+38.1%</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="honest-limitations" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="honest-limitations"><span class="header-section-number">10.2</span> Honest Limitations</h3>
<ol type="1">
<li><p><strong>JEPA does not capture spectral centroid shift</strong> (primary RUL indicator). Max per-dim correlation: 0.144 vs 0.585 for spectral centroid.</p></li>
<li><p><strong>JEPA pretraining is unstable</strong> on heterogeneous multi-source data. Loss oscillates after epoch 2; best checkpoint is always early.</p></li>
<li><p><strong>Only 23 episodes</strong> (16 FEMTO + 7 XJTU-SY). 5-seed results have high variance.</p></li>
<li><p><strong>Temporal contrastive requires run-to-failure episode structure.</strong> Self-supervised but not label-free.</p></li>
<li><p><strong>Cross-dataset comparison is limited</strong> to two datasets with different operating conditions.</p></li>
</ol>
</section>
<section id="novel-contribution" class="level3" data-number="10.3">
<h3 data-number="10.3" class="anchored" data-anchor-id="novel-contribution"><span class="header-section-number">10.3</span> Novel Contribution</h3>
<p>Temporal contrastive pretraining using run-to-failure episode structure learns spectral centroid-aligned representations that transfer cross-dataset. This is the first demonstration of JEPA vs contrastive for RUL% prediction with a mechanistic explanation of why contrastive transfers better. The hybrid JEPA+HC result (0.055 RMSE, +75.5% vs time-only) shows JEPA captures waveform features orthogonal to handcrafted spectral statistics.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="appendix-pretraining-configurations" class="level2 appendix" data-number="11"><h2 class="anchored quarto-appendix-heading"><span class="header-section-number">11</span> Appendix: Pretraining Configurations</h2><div class="quarto-appendix-contents">

<div id="tbl-configs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Hyperparameter configurations explored
</figcaption>
<div aria-describedby="tbl-configs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 30%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Config</th>
<th>LR</th>
<th>EMA</th>
<th>Mask</th>
<th>Best Val Loss</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>JEPA default</td>
<td>1e-4</td>
<td>0.996</td>
<td>62.5%</td>
<td>0.0166 (ep2)</td>
<td><strong>Use</strong></td>
</tr>
<tr class="even">
<td>JEPA lower LR</td>
<td>3e-5</td>
<td>0.996</td>
<td>62.5%</td>
<td>0.0172</td>
<td>Similar</td>
</tr>
<tr class="odd">
<td>JEPA fixed LR</td>
<td>1e-5</td>
<td>0.996</td>
<td>62.5%</td>
<td>0.0189</td>
<td>Worse</td>
</tr>
<tr class="even">
<td>JEPA high EMA</td>
<td>1e-4</td>
<td>0.999</td>
<td>62.5%</td>
<td>0.0178</td>
<td>Worse</td>
</tr>
<tr class="odd">
<td>JEPA 2ch FFT</td>
<td>1e-4</td>
<td>0.996</td>
<td>62.5%</td>
<td>0.0149</td>
<td>Better loss, worse RUL</td>
</tr>
<tr class="even">
<td>Contrastive (narrow)</td>
<td>1e-4</td>
<td>—</td>
<td>—</td>
<td>0.2477</td>
<td><strong>Best cross-domain</strong></td>
</tr>
<tr class="odd">
<td>Contrastive (broad)</td>
<td>1e-4</td>
<td>—</td>
<td>—</td>
<td>0.0093</td>
<td>Worse downstream</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>